#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# makefile for Java SDDS Editor
# $Log: not supported by cvs2svn $
# Revision 1.3  2002/06/24 15:44:07  soliday
# Changed the JARCMD option.
#
# Revision 1.2  2001/06/05 18:49:04  soliday
# Changed package name.
#
# Revision 1.1  2000/05/09 21:22:06  soliday
# First version.
#
#
#
#

TOP = ../../../..
include $(TOP)/configure/CONFIG

JAR = SDDSplot.jar
JAR_PACKAGES = SDDS/java/SDDSplot
JAVACFLAGS += -O

JAVA = TickInterval.java plotApplet.java

include $(TOP)/configure/RULES

